In [0]:
import pandas as pd
import numpy as np

# Read the CSV and Perform Basic Data Cleaning

In [97]:
df = pd.read_csv("cumulative.csv")
df = df.drop(columns=["rowid", "kepid", "kepoi_name", "kepler_name", "koi_pdisposition", "koi_score", "koi_tce_delivname"])
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head(20)

koi_disposition  koi_fpflag_nt  ...        dec  koi_kepmag
0        CONFIRMED              0  ...  48.141651      15.347
1        CONFIRMED              0  ...  48.141651      15.347
2   FALSE POSITIVE              0  ...  48.134129      15.436
3   FALSE POSITIVE              0  ...  48.285210      15.597
4        CONFIRMED              0  ...  48.226200      15.509
5        CONFIRMED              0  ...  48.224670      15.714
6        CONFIRMED              0  ...  48.224670      15.714
7        CONFIRMED              0  ...  48.224670      15.714
8   FALSE POSITIVE              0  ...  42.151569      12.660
9        CONFIRMED              0  ...  48.375790      15.841
10       CONFIRMED              0  ...  49.316399      11.338
11       CONFIRMED              0  ...  47.969521      10.463
12       CONFIRMED              0  ...  42.451080      13.563
13       CONFIRMED              0  ...  48.495560      12.772
14  FALSE POSITIVE              0  ...  47.597401      15.472
15  FALSE POSITIVE              0  ...  47.635319      15.487
16  FALSE POSITIVE              0  ...  47.690350      15.341
17  FALSE POSITIVE              0  ...  47.668701      15.788
18       CONFIRMED              0  ...  47.724449      15.302
19       CONFIRMED              0  ...  47.863270      15.784

[20 rows x 41 columns]

In [98]:

#Creating the results
y = df["koi_disposition"]
print(y)

0            CONFIRMED
1            CONFIRMED
2       FALSE POSITIVE
3       FALSE POSITIVE
4            CONFIRMED
5            CONFIRMED
6            CONFIRMED
7            CONFIRMED
8       FALSE POSITIVE
9            CONFIRMED
10           CONFIRMED
11           CONFIRMED
12           CONFIRMED
13           CONFIRMED
14      FALSE POSITIVE
15      FALSE POSITIVE
16      FALSE POSITIVE
17      FALSE POSITIVE
18           CONFIRMED
19           CONFIRMED
20      FALSE POSITIVE
21           CONFIRMED
22           CONFIRMED
23           CONFIRMED
24      FALSE POSITIVE
25           CONFIRMED
26           CONFIRMED
27           CONFIRMED
28      FALSE POSITIVE
29      FALSE POSITIVE
             ...      
9532    FALSE POSITIVE
9533         CANDIDATE
9535    FALSE POSITIVE
9536    FALSE POSITIVE
9537    FALSE POSITIVE
9538    FALSE POSITIVE
9539         CANDIDATE
9540         CONFIRMED
9541    FALSE POSITIVE
9542         CANDIDATE
9543    FALSE POSITIVE
9544         CANDIDATE
9545    FAL

In [99]:
#Creating the frame for x

df = df.drop(columns = ["koi_disposition"])

print(df.columns)

X = df [['koi_fpflag_nt', 'koi_fpflag_ss', 'koi_fpflag_co',
       'koi_fpflag_ec', 'koi_period', 'koi_period_err1', 'koi_period_err2',
       'koi_time0bk', 'koi_time0bk_err1', 'koi_time0bk_err2', 'koi_impact',
       'koi_impact_err1', 'koi_impact_err2', 'koi_duration',
       'koi_duration_err1', 'koi_duration_err2', 'koi_depth', 'koi_depth_err1',
       'koi_depth_err2', 'koi_prad', 'koi_prad_err1', 'koi_prad_err2',
       'koi_teq', 'koi_insol', 'koi_insol_err1', 'koi_insol_err2',
       'koi_model_snr', 'koi_tce_plnt_num', 'koi_steff', 'koi_steff_err1',
       'koi_steff_err2', 'koi_slogg', 'koi_slogg_err1', 'koi_slogg_err2',
       'koi_srad', 'koi_srad_err1', 'koi_srad_err2', 'ra', 'dec',
       'koi_kepmag']]

print(X.shape)


Index(['koi_fpflag_nt', 'koi_fpflag_ss', 'koi_fpflag_co', 'koi_fpflag_ec',
       'koi_period', 'koi_period_err1', 'koi_period_err2', 'koi_time0bk',
       'koi_time0bk_err1', 'koi_time0bk_err2', 'koi_impact', 'koi_impact_err1',
       'koi_impact_err2', 'koi_duration', 'koi_duration_err1',
       'koi_duration_err2', 'koi_depth', 'koi_depth_err1', 'koi_depth_err2',
       'koi_prad', 'koi_prad_err1', 'koi_prad_err2', 'koi_teq', 'koi_insol',
       'koi_insol_err1', 'koi_insol_err2', 'koi_model_snr', 'koi_tce_plnt_num',
       'koi_steff', 'koi_steff_err1', 'koi_steff_err2', 'koi_slogg',
       'koi_slogg_err1', 'koi_slogg_err2', 'koi_srad', 'koi_srad_err1',
       'koi_srad_err2', 'ra', 'dec', 'koi_kepmag'],
      dtype='object')
(8744, 40)


In [100]:
#Preprocessing done before the Train Test Split 

import sklearn.preprocessing as skprep
scaler = skprep.MinMaxScaler()
print(scaler)
scaler.fit(X)
X = scaler.transform(X)
print(X)

MinMaxScaler(copy=True, feature_range=(0, 1))
[[0.         0.         0.         ... 0.55247338 0.73383732 0.69270188]
 [0.         0.         0.         ... 0.55247338 0.73383732 0.69270188]
 [0.         1.         0.         ... 0.78434556 0.73335999 0.70005786]
 ...
 [0.         0.         0.         ... 0.30440085 0.67174867 0.64393752]
 [0.         0.         1.         ... 0.65447887 0.67257754 0.69584263]
 [0.         0.         1.         ... 0.78457191 0.66907089 0.64964047]]


# Create a Train Test Split

Use `koi_disposition` for the y values

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [102]:
X_train

array([[1.        , 0.        , 0.        , ..., 0.38747277, 0.28240001,
        0.72047277],
       [0.        , 0.        , 0.        , ..., 0.58253597, 0.11563677,
        0.65608728],
       [0.        , 0.        , 1.        , ..., 0.71602027, 0.40315588,
        0.54839243],
       ...,
       [0.        , 1.        , 0.        , ..., 0.66083517, 0.22940936,
        0.7311348 ],
       [0.        , 0.        , 0.        , ..., 0.69145612, 0.54803695,
        0.54665675],
       [0.        , 0.        , 1.        , ..., 0.74376213, 0.7172228 ,
        0.67980825]])

# Pre-processing

Scale the data using the MinMaxScaler

In [103]:
#Checking the shapes
print(X_train.shape, y_train.shape)

(6558, 40) (6558,)


# Train the Support Vector Machine

In [0]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=200)
rf.fit(X_train, y_train)
predictions = rf.predict(X_test)

In [105]:
# Random Forests in sklearn will automatically calculate feature importance
importances = rf.feature_importances_
importances

array([0.10301713, 0.07480579, 0.1041685 , 0.03369741, 0.0204213 ,
       0.01779789, 0.01830852, 0.01371801, 0.02315319, 0.02416068,
       0.01808538, 0.01103407, 0.01017354, 0.02492507, 0.03445087,
       0.03278151, 0.0201614 , 0.01442248, 0.01349625, 0.04507761,
       0.02476385, 0.03700741, 0.0155441 , 0.01347578, 0.01763371,
       0.01283604, 0.05332032, 0.0032025 , 0.00976613, 0.03474446,
       0.02872394, 0.00942656, 0.00865199, 0.00976673, 0.00930042,
       0.01255246, 0.00912248, 0.01164177, 0.01072141, 0.00994135])

In [106]:
# We can sort the features by their importance
sorted(zip(rf.feature_importances_, df.columns), reverse=True)

[(0.1041684953453861, 'koi_fpflag_co'),
 (0.10301712645034183, 'koi_fpflag_nt'),
 (0.07480578538905346, 'koi_fpflag_ss'),
 (0.053320317791998126, 'koi_model_snr'),
 (0.04507761416985842, 'koi_prad'),
 (0.03700740986174169, 'koi_prad_err2'),
 (0.03474445942313464, 'koi_steff_err1'),
 (0.03445087266502811, 'koi_duration_err1'),
 (0.03369741188266821, 'koi_fpflag_ec'),
 (0.032781508582343084, 'koi_duration_err2'),
 (0.028723942043912674, 'koi_steff_err2'),
 (0.024925067460807634, 'koi_duration'),
 (0.024763852725473358, 'koi_prad_err1'),
 (0.024160681299845752, 'koi_time0bk_err2'),
 (0.02315319403395928, 'koi_time0bk_err1'),
 (0.02042130211609662, 'koi_period'),
 (0.020161401780997065, 'koi_depth'),
 (0.018308515643114767, 'koi_period_err2'),
 (0.018085381364368464, 'koi_impact'),
 (0.017797893645179915, 'koi_period_err1'),
 (0.01763371064366888, 'koi_insol_err1'),
 (0.015544096560131235, 'koi_teq'),
 (0.01442247807698539, 'koi_depth_err1'),
 (0.013718010119622441, 'koi_time0bk'),
 (0.013

In [107]:
print(f"Training Data Score: {rf.score(X_train, y_train)}")
print(f"Testing Data Score: {rf.score(X_test, y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.8870082342177493


# Hyperparameter Tuning

Use `GridSearchSearchCV` to tune the `n_estimators` and `max_features` parameters

In [108]:
from pprint import pprint
# Look at parameters used by our current forest - n_estimators has been set to 200
print('Parameters currently in use:\n')
pprint(rf.get_params())

Parameters currently in use:

{'bootstrap': True,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 200,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}


In [0]:
from sklearn.model_selection import GridSearchCV
param_grid = {'n_estimators': [100, 200, 300, 500],
              'max_features': ['auto', 'sqrt']}
grid = GridSearchCV(rf, param_grid, verbose=3)

In [110]:
# Train the model with GridSearch

# Fit the model using the grid search estimator. 
# This will take the SVC model and try each combination of parameters
grid.fit(X_train, y_train)

Fitting 3 folds for each of 8 candidates, totalling 24 fits
[CV] max_features=auto, n_estimators=100 .............................


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] . max_features=auto, n_estimators=100, score=0.890, total=   1.8s
[CV] max_features=auto, n_estimators=100 .............................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.8s remaining:    0.0s


[CV] . max_features=auto, n_estimators=100, score=0.887, total=   1.8s
[CV] max_features=auto, n_estimators=100 .............................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    3.7s remaining:    0.0s


[CV] . max_features=auto, n_estimators=100, score=0.896, total=   1.8s
[CV] max_features=auto, n_estimators=200 .............................
[CV] . max_features=auto, n_estimators=200, score=0.896, total=   3.6s
[CV] max_features=auto, n_estimators=200 .............................
[CV] . max_features=auto, n_estimators=200, score=0.892, total=   3.7s
[CV] max_features=auto, n_estimators=200 .............................
[CV] . max_features=auto, n_estimators=200, score=0.898, total=   3.6s
[CV] max_features=auto, n_estimators=300 .............................
[CV] . max_features=auto, n_estimators=300, score=0.893, total=   5.4s
[CV] max_features=auto, n_estimators=300 .............................
[CV] . max_features=auto, n_estimators=300, score=0.891, total=   5.5s
[CV] max_features=auto, n_estimators=300 .............................
[CV] . max_features=auto, n_estimators=300, score=0.900, total=   5.4s
[CV] max_features=auto, n_estimators=500 .............................
[CV] .

[Parallel(n_jobs=1)]: Done  24 out of  24 | elapsed:  2.0min finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=200, n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             i

In [111]:
print(grid.best_params_)
print(grid.best_score_)

{'max_features': 'auto', 'n_estimators': 200}
0.8953949374809393


In [112]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=["CONFIRMED", "CANDIDATE", "FALSE POSITIVE"]))

                precision    recall  f1-score   support

     CONFIRMED       0.80      0.74      0.77       511
     CANDIDATE       0.81      0.81      0.81       588
FALSE POSITIVE       0.97      1.00      0.98      1087

      accuracy                           0.89      2186
     macro avg       0.86      0.85      0.85      2186
  weighted avg       0.88      0.89      0.89      2186

